### ISSUE TITLE
The actions are not working for me!

### ISSUE THREAD

**Issue by johnsidi** [beet/joplin_alfred_actions#3]
Are these actions still working?

I think I have set up correctly the base directory:  /OneDrive/Apps/Joplin 

I use macOS Mojave 10.14.6, Alfred 4.0.9 and Joplin 1.0.216

When I tried to activate the jba action I got the following error from the Alfred Debugger

```[08:47:54.265] Jopliin Actions[Script Filter] Script with argv '(null)' finished
[08:47:54.272] ERROR: Jopliin Actions[Script Filter] Code 1: /Users/is/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.01D658D6-FE84-48D4-A66C-108A9F272FCC/lib/joplin/note_file.rb:36:in `is_metadata?': undefined method `match?' for "2pzk9b484806cd0e8406789d77c0c78f50931":String (NoMethodError)
Did you mean?  match
	from /Users/is/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.01D658D6-FE84-48D4-A66C-108A9F272FCC/lib/joplin/note_file.rb:32:in `is_note?'
	from /Users/is/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.01D658D6-FE84-48D4-A66C-108A9F272FCC/lib/joplin/notes_list.rb:16:in `block (2 levels) in alfred_items'
	from /Users/is/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.01D658D6-FE84-48D4-A66C-108A9F272FCC/lib/joplin/base.rb:30:in `block in for_each_note'
	from /Users/is/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.01D658D6-FE84-48D4-A66C-108A9F272FCC/lib/joplin/base.rb:29:in `glob'
	from /Users/is/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.01D658D6-FE84-48D4-A66C-108A9F272FCC/lib/joplin/base.rb:29:in `for_each_note'
	from /Users/is/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.01D658D6-FE84-48D4-A66C-108A9F272FCC/lib/joplin/notes_list.rb:15:in `block in alfred_items'
	from /Users/is/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.01D658D6-FE84-48D4-A66C-108A9F272FCC/lib/joplin/notes_list.rb:14:in `tap'
	from /Users/is/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.01D658D6-FE84-48D4-A66C-108A9F272FCC/lib/joplin/notes_list.rb:14:in `alfred_items'
	from /Users/is/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.01D658D6-FE84-48D4-A66C-108A9F272FCC/lib/joplin/base.rb:21:in `json'
	from /Users/is/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/8BE51845-D424-4500-9F49-0AF07D787F8A:4:in `<main>'
```

Any help is greatly appreciated!

**Comment by beet** [comment]
So sorry to have missed this, I have email notifications turned on, but didn't see it.

Is it only the browse in Alfred action that doesn't work, or do the other actions like inserting wiki links with `jwl` work?

That error, "undefined method `match?'", looks like it could be a Ruby version mismatch.

Could you try the following please?

* Right click on the workflow in Alfred and select "Open in Terminal"
* Enter the following: `ruby --version`

I think I can see the mistake that I've made, I'm running 2.6.4 through rbenv, but you could be using the macOS system default Ruby. To find out, try `which ruby`.

It's possible that `match?` isn't available in earlier versions of Ruby, in which case I can re-factor it to use a different method that's available to earlier versions of Ruby.
